file(MAKE_DIRECTORY ${TEST_WORK_DIR})

message(STATUS "Compressing ${ORIG_FILE}")
execute_process(
    COMMAND ${HFM_EXECUTABLE} ${ORIG_FILE} -o ${COMPRESSED_FILE}
    RESULT_VARIABLE COMPRESS_RESULT
    OUTPUT_VARIABLE COMPRESS_OUT ERROR_VARIABLE COMPRESS_ERR
)
if(NOT COMPRESS_RESULT EQUAL 0)
    message(FATAL_ERROR "Compression failed: ${COMPRESS_ERR}")
endif()

message(STATUS "Decompressing ${COMPRESSED_FILE}")
execute_process(
    COMMAND ${HFM_EXECUTABLE} -d ${COMPRESSED_FILE} -o ${DECOMPRESSED_FILE}
    RESULT_VARIABLE DECOMPRESS_RESULT
    OUTPUT_VARIABLE DECOMPRESS_OUT ERROR_VARIABLE DECOMPRESS_ERR
)
if(NOT DECOMPRESS_RESULT EQUAL 0)
    message(FATAL_ERROR "Decompression failed: ${DECOMPRESS_ERR}")
endif()

message(STATUS "Comparing ${ORIG_FILE} with ${DECOMPRESSED_FILE}")
execute_process(
    COMMAND ${CMAKE_COMMAND} -E compare_files ${ORIG_FILE} ${DECOMPRESSED_FILE}
    RESULT_VARIABLE COMPARE_RESULT
)
if(NOT COMPARE_RESULT EQUAL 0)
    message(FATAL_ERROR "Files differ after roundtrip!")
endif()

message(STATUS "Test passed for ${ORIG_FILE}")
