name: Build hfm

on: [push, pull_request]

jobs:
  clang-format:
    name: Check code style
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: sudo apt update && sudo apt install -y clang-format
      - name: Checkout
        uses: actions/checkout@v6.0.2
      - name: Run clang-format
        run: clang-format --dry-run -Werror `git ls-files 'src/*.c' 'src/*.h'`
